import MySQLdb
con=MySQLdb.connect(host="localhost",user="root",password="root",db="employeedb")
cur=con.cursor()
empid=input("Enter empid ")
#email=input("Enter Employee mail ")
result=cur.execute("delete from employee where Empid=%s",[empid])
print(result, "records updated")
cur.close()
con.commit()
con.close()
